matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    services:
    - docker
    cache:
      directories:
      - "$HOME/.npm"
      - ".git"
    env:
    - builder=travis
language: node_js
node_js:
- 8
addons:
  apt:
    packages:
    - curl
    - socat
    - python3-pip
    - time
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip3 install hovercraft; fi
script:
- /bin/bash -l -c "/usr/bin/time -v make -e ci"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: build
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
